### PR TITLE
Refactor with remote exporter

### PR DESCRIPTION
**Pull request by yrong**
Context in https://github.com/paritytech/polkadot-sdk/pull/2522#discussion_r1425289690

### CODE REVIEW

**Review by claravanstaden — APPROVED** [review]
Awesome, looks great!

**Review by alistair-singh — APPROVED** [review]
+1

**Comment by yrong** [comment]
@alistair-singh Add the check to ensure `BridgeHubEthereumBaseFee` charged in https://github.com/Snowfork/polkadot-sdk/pull/71/commits/79f62940fdd1fbbee5242dac08a2b49560a9dd90

**Comment by yrong** [comment]
@claravanstaden There are some comments for the format change in https://github.com/Snowfork/polkadot-sdk/pull/71, Please check if it's necessary or not.

**Comment by claravanstaden** [comment]
Hey @yrong, sorry about that. Fix here: https://github.com/Snowfork/polkadot-sdk/pull/76

**Pull request merged**
