### PR TITLE
Parachain commitment parachain proof

### PR DESCRIPTION
**Pull request by musnit**
Draft of creating merkle proof of our parachain's header within the relayer. Still not working. Debugging/comparing to the Rust code still todo.

### CODE REVIEW

**Comment by musnit** [comment]
@tomusdrw tagging you here for help too - busy trying to debug using the scripts in https://github.com/paritytech/grandpa-bridge-gadget/blob/master/beefy-cli/src/cli/merkle_tree.rs but not seeing where the mismatch is. any ideas?

one example:
 - relayer output:
```
time="2021-06-15T23:37:21Z" level=info msg="Got all parachain headers" worker=parachain-commitment-relayer
time="2021-06-15T23:37:21Z" level=info msg="Decoding header for parachain" parachainId=200 worker=parachain-commitment-relayer
time="2021-06-15T23:37:21Z" level=info msg="Decoded header for parachain" header.Digest="[]" header.ExtrinsicsRoot=0x6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f66 header.Number=149 header.ParentHash=0xc9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a8648 header.StateRoot=0xefb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b headerBytes=0xc9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600 parachainId=200 worker=parachain-commitment-relayer
parachain-commitment-relayer allParaHeadsBytes [[201 239 213 28 126 181 113 8 235 114 186 37 59 212 112 153 227 199 125 196 218 24 236 58 201 196 112 207 25 138 134 72 85 2 239 184 116 102 70 10 165 63 227 95 53 236 179 45 33 200 82 164 165 140 88 15 6 168 82 30 216 33 131 89 234 27 106 38 68 196 197 113 61 93 134 216 102 205 19 135 6 95 113 79 246 73 199 99 92 88 73 181 32 134 230 151 79 102 0] [155 221 38 217 180 71 250 179 72 46 38 68 52 155 73 87 141 184 232 165 81 59 60 214 171 29 60 138 207 191 38 150 61 2 88 232 119 194 106 69 61 42 1 40 178 109 28 176 31 116 124 93 46 169 33 17 100 170 154 143 79 249 70 139 216 42 135 228 174 118 61 243 124 250 131 120 68 185 160 240 74 82 130 159 143 125 242 166 126 66 220 98 71 77 20 193 238 49 0]]
parachain-commitment-relayer allParaHeadsBytesHex 0x088d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f66008d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100
parachain-commitment-relayer paraHeadBytes0Hex 0x8d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600
parachain-commitment-relayer paraHeadBytes1Hex 0x8d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100
parachain-commitment-relayer paraHeadBytesHex 0x8d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600 0x8d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100
parachain-commitment-relayer ourParaHeadBytes [201 239 213 28 126 181 113 8 235 114 186 37 59 212 112 153 227 199 125 196 218 24 236 58 201 196 112 207 25 138 134 72 85 2 239 184 116 102 70 10 165 63 227 95 53 236 179 45 33 200 82 164 165 140 88 15 6 168 82 30 216 33 131 89 234 27 106 38 68 196 197 113 61 93 134 216 102 205 19 135 6 95 113 79 246 73 199 99 92 88 73 181 32 134 230 151 79 102 0]
parachain-commitment-relayer ourParaHeadBytesHex 0x8d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600
parachain-commitment-relayer root 0x800eb84609e4806eb2de06d641770c3f25bf998d362460cbf079121fa906ddb402
parachain-commitment-relayer proof &{[[54 38 118 91 141 169 160 146 209 64 153 47 20 139 199 103 23 104 206 208 182 181 207 167 223 73 3 143 206 20 33 56]] 0}
parachain-commitment-relayer len(proof.Hashes) 1
parachain-commitment-relayer proofContents [[54 38 118 91 141 169 160 146 209 64 153 47 20 139 199 103 23 104 206 208 182 181 207 167 223 73 3 143 206 20 33 56]]
parachain-commitment-relayer proofContents0Hex 0x3626765b8da9a092d140992f148bc7671768ced0b6b5cfa7df49038fce142138
time="2021-06-15T23:37:21Z" level=info msg=BeefyMMRLeafParachainHeads ParachainHeads=0x93d69747fa980183f9cfeaf95b26d37cf9b7b9b5e13d16fc92a266a257836154 worker=parachain-commitment-relayer
```

- output from the merkle_tree script:
```
➜  grandpa-bridge-gadget git:(master) cargo run -p beefy-cli -- para-heads-merkle-tree generate-proof 0 0x8d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600 0x8d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/beefy-cli para-heads-merkle-tree generate-proof 0 0x8d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600 0x8d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100`

Root: 0x80abe1fa3e5e914673ee532d5d16d2b4d177ccf24e6face3f1dbf1b7463006c8
SCALE-encoded proof: 0x089881001100008055a1a4ebd8b13877768f4145614010645e677cd2f5f5b18c320a7cfc8e082bed084000

Leaf key: 0x00
SCALE-encoded leaf value: 0x95018d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600
```
```
➜  grandpa-bridge-gadget git:(master) cargo run -p beefy-cli -- para-heads-merkle-tree generate-proof 1 0x8d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600 0x8d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/beefy-cli para-heads-merkle-tree generate-proof 1 0x8d01c9efd51c7eb57108eb72ba253bd47099e3c77dc4da18ec3ac9c470cf198a86485502efb87466460aa53fe35f35ecb32d21c852a4a58c580f06a8521ed8218359ea1b6a2644c4c5713d5d86d866cd1387065f714ff649c7635c5849b52086e6974f6600 0x8d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100`

Root: 0x80abe1fa3e5e914673ee532d5d16d2b4d177ccf24e6face3f1dbf1b7463006c8
SCALE-encoded proof: 0x089881001100803eaebd4fe9fc3f8519ad32ef0d19ec2b628c8bd091aa3350927a48d6e1bc021900084000

Leaf key: 0x04
SCALE-encoded leaf value: 0x95018d019bdd26d9b447fab3482e2644349b49578db8e8a5513b3cd6ab1d3c8acfbf26963d0258e877c26a453d2a0128b26d1cb01f747c5d2ea9211164aa9a8f4ff9468bd82a87e4ae763df37cfa837844b9a0f04a52829f8f7df2a67e42dc62474d14c1ee3100
```

**Comment by tomusdrw** [comment]
@musnit can you check https://github.com/paritytech/grandpa-bridge-gadget/pull/214 ? I have no idea how I've tested that before, but it seems that the trie generation was all incorrect in the CLI.

**Comment by musnit** [comment]
@tomusdrw same output with new cli version

**Comment by musnit** [comment]
replacing with https://github.com/Snowfork/snowbridge/pull/448

**Pull request closed without merging**
