### PR TITLE
Lodestar 1.4.2 update

### PR DESCRIPTION
**Pull request by claravanstaden**
Lodestar upgrade. Blocked by an issue where the `finalized_header` is empty for sync committee updates.

### CODE REVIEW

**Comment by claravanstaden** [comment]
Fixed by https://github.com/ChainSafe/lodestar/pull/5090. Waiting for Lodestar release `1.4.2` to include the fix.

**Comment by yrong** [comment]
@claravanstaden  one [issue](https://github.com/ChainSafe/lodestar/issues/5100) I met maybe also worth to mention here

**Comment by claravanstaden** [comment]
> would assume the https://github.com/ChainSafe/lodestar/pull/5073 in 1.4.1 also related to the weird issue we met before in some mac os. hope with it no need to hack in /etc/hosts or explicitly adding 127.0.0.1 any more.

@yrong is this still an issue for you on lodestar 1.4.2?

**Review by alistair-singh — APPROVED** [review]
🚢

**Comment by claravanstaden** [comment]
I'm going to merge this now because I would like to rebase my ancestry proof branch. I'll address any follow-up comments in a separate PR, if necessary.

**Comment by yrong** [comment]
> @yrong is this still an issue for you on lodestar 1.4.2? Edit: Looks like it is solved in 1.4.1 but you can perhaps retest and confirm.

Sorry for the late response and yes it works in my setup

**Pull request merged**
