### PR TITLE
Fix build image

### PR DESCRIPTION
**Pull request by yrong**

### CODE REVIEW

**Comment by yrong** [comment]
I made some change in this PR but still get the errors when pushing the image:

```
#15 ERROR: denied: permission_denied: write_package
------
 > pushing ghcr.io/snowfork/snowbridge-relay:relayer-fix-build-relayer-1.0.1 with docker:
------
ERROR: denied: permission_denied: write_package
```
More details in https://github.com/Snowfork/snowbridge/actions/runs/10500398441/job/29088724680.

@vgeddes Could you please check whether we config the `GITHUB_TOKEN` with sufficient scopes?

**Comment by vgeddes** [comment]
> I made some fix in this PR but still get the errors when pushing the image, error as:
> 
> ```
> #15 ERROR: denied: permission_denied: write_package
> ------
>  > pushing ghcr.io/snowfork/snowbridge-relay:relayer-fix-build-relayer-1.0.1 with docker:
> ------
> ERROR: denied: permission_denied: write_package
> ```
> 
> More details in https://github.com/Snowfork/snowbridge/actions/runs/10500398441/job/29088724680.
> 
> @vgeddes Could you please check whether we config the `GITHUB_TOKEN` with sufficient scopes?

There is no `GITHUB_TOKEN`  actions secret registered for the repo

**Comment by vgeddes** [comment]
can you check in the github docs about what we need to configure in order to push to github packages ?

**Comment by yrong** [comment]
> There is no GITHUB_TOKEN actions secret registered for the repo

It's an automatic token https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication

> can you check in the github docs about what we need to configure in order to push to github packages ?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions

**Comment by vgeddes** [comment]
OK can you try again. I had to allow the `snowbridge` write access to the package via github actions. A different setting to what you suggested.

**Comment by yrong** [comment]
> OK can you try again. I had to allow the `snowbridge` repo write access to the package via github actions. A different setting to what you suggested.

Thanks, it works now. https://github.com/Snowfork/snowbridge/actions/runs/10538273949/job/29200602546

**Pull request merged**
