### PR TITLE
Update upstream

### PR DESCRIPTION
**Pull request by yrong**
Tested that smoke tests worked as expected.

### CODE REVIEW

**Comment by claravanstaden** [comment]
I made a duplicate PR over here: https://github.com/Snowfork/snowbridge/pull/1290 😅 I can close it, but perhaps take a look and see if you agree we should rather work off a personal fork, right? I guess it doesn't really make sense since you can just add another git remote to your personal fork.

**Comment by yrong** [comment]
> I made a duplicate PR over here: #1290 😅 I can close it, but perhaps take a look and see if you agree we should rather work off a personal fork, right? I guess it doesn't really make sense since you can just add another git remote to your personal fork.

Yeah, I'm not sure whether the personal fork is required or not. Can we just work on a feature branch in https://github.com/Snowfork/polkadot-sdk as before?

**Comment by claravanstaden** [comment]
> Yeah, I'm not sure whether the personal fork is required or not. For new features can we just work on a feature branch in https://github.com/Snowfork/polkadot-sdk as before?

I am referring to @vgeddes message on Slack: https://snowfork.slack.com/archives/G01BGMGLAC9/p1726175630533599?thread_ts=1726087855.732099&cid=G01BGMGLAC9

**Comment by vgeddes** [comment]
Yeah as per the slack convo and discussions with Parity we should stop using https://github.com/Snowfork/polkadot-sdk entirely.

By default the smoke tests should run against https://github.com/paritytech/polkadot-sdk, unless overridden using a personal fork.

**Comment by yrong** [comment]
Closed in favor of https://github.com/Snowfork/snowbridge/pull/1290

**Pull request closed without merging**
