### PR TITLE
Updates for sepolia

### PR DESCRIPTION
**Pull request by yrong**
As recommend by https://blog.ethereum.org/2024/01/24/sepolia-holesky-dencun upgrade

- geth: 1.13.11
- lodestar: 1.15.0-rc.0

It's also better to update our rococo deployment accordingly.

### CODE REVIEW

**Comment by claravanstaden** [comment]
Did you run the smoke tests against these versions?

Can we run Lodestar 1.14.0? Not sure if we should run a release candidate

**Comment by alistair-singh** [comment]
> Did you run the smoke tests against these versions?
> 
> Can we run Lodestar 1.14.0? Not sure if we should run a release candidate

In Rococo-Sepolia we are running:
* Geth Docker image [v1.13.11](https://hub.docker.com/layers/ethereum/client-go/v1.13.11/images/sha256-5efa745d1cc12a64a3eb900f097e2481686d2f350260911d5ab7d564660c6568?context=explore)
* Lodestar Docker image [v1.15.0](https://hub.docker.com/layers/chainsafe/lodestar/v1.15.0/images/sha256-e3db7500d66ac74704bb4bff18939e9bdadf194b2754f963cf659bbb5be39fa6?context=explore)

They seem to have 1.15.0 image maybe we should use that in our testnet?

**Comment by yrong** [comment]
> They seem to have 1.15.0 image maybe we should use that in our testnet?

@alistair-singh Thanks for updating that in testnet,  I also updated accordingly here.

> Did you run the smoke tests against these versions?

@claravanstaden  Yeah, work as expected.

**Comment by yrong** [comment]
> Did you run the smoke tests against these versions?

@claravanstaden Yeah, works as expected.

**Review by claravanstaden — APPROVED** [review]

**Review by vgeddes — APPROVED** [review]

**Pull request merged**
