### PR TITLE
Pre audit fixes

### PR DESCRIPTION
**Pull request by philipstanislaus**
See commit messages for details

### CODE REVIEW

**Review by musnit — APPROVED** [review]

**Comment by musnit** [comment]
iff all e2e and unit tests pass still, then good to merge.

**Comment by philipstanislaus** [comment]
@musnit ethereum tests all pass, but I could not get my e2e test environment to work, it outputs the following error: 

```
Deploying contracts
Nothing to compile
failed to get chainId, falling back on net_version...
Error HH108: Cannot connect to the network localhost.
Please make sure your node is running, and check your internet connection and networks config
```

Would you take this over from here since I'm OOO now? 

Many thanks!

**Comment by musnit** [comment]
> @musnit ethereum tests all pass, but I could not get my e2e test environment to work, it outputs the following error:
> 
> ```
> Deploying contracts
> Nothing to compile
> failed to get chainId, falling back on net_version...
> Error HH108: Cannot connect to the network localhost.
> Please make sure your node is running, and check your internet connection and networks config
> ```
> 
> Would you take this over from here since I'm OOO now?
> 
> Many thanks!

hm maybe we are missing something in our instructions for setting up Geth. Did you follow test/README again fully? Anyway, will do.

**Comment by musnit** [comment]
@vgeddes going to merge this, but I'm adding you as a reviewer to run through for when you're back.

**Comment by philipstanislaus** [comment]
> hm maybe we are missing something in our instructions for setting up Geth. Did you follow test/README again fully? Anyway, will do.

Yeah, the error indicate it’s related to geht setup. I did follow all the steps. Will retry when back. 

Thanks for wrapping this up!

**Pull request merged**
