### PR TITLE
Derive AgentId for BridgeHub in a consistent manner

### PR DESCRIPTION
**Pull request by yrong**
Resolves: SNO-760

### CODE REVIEW

**Comment by vgeddes** [comment]
Looks good so far. Of course, if the junction is not `Here`, we should pass it to `xcm_builder::DescribeFamily`.

**Comment by vgeddes** [comment]
And of course then we would no longer need to hardcode the AgentID here: https://github.com/Snowfork/snowbridge/blob/d97e3b780953edfb5296e83bcbb850c66caafe57/parachain/primitives/core/src/lib.rs#L139. Can delete it.

**Review by alistair-singh — APPROVED** [review]
🚀

**Comment by yrong** [comment]
Merge though integration tests failed,  will handle that in other PRs more related.

**Pull request merged**
