### PR TITLE
Configurable dispatch gas

### PR DESCRIPTION
**Pull request by yrong**
Resolves: SNO-650

### CODE REVIEW

**Comment by vgeddes** [comment]
Looks good so far 👌

**Comment by vgeddes** [comment]
As discussed with @musnit we may also want to include relayer reward in the message to the Gateway, to make the messaging protocol more declarative (also known as _intents_ in DeFi terminology).

But let's confirm this first in our meeting tomorrow.

**Comment by yrong** [comment]
> we may also want to include relayer reward in the message to the Gateway, to make the messaging protocol more declarative

Agree. The reward should not be some config per channel as we do now. It seems more like the config for each kind of the message(i.e. incentivize relayer with more reward for a heavy dispatch).

**Comment by yrong** [comment]
Closed in favor of https://github.com/Snowfork/snowbridge/pull/940

**Pull request closed without merging**
