### PR TITLE
Use cumulus package versions

### PR DESCRIPTION
**Pull request by alistair-singh**
* serde_json = "1.0.96"
* serde = "1.0.160"
* hex-literal = "0.4.1"

Cumulus Companion: https://github.com/Snowfork/cumulus/pull/16

### CODE REVIEW

**Review by vgeddes — APPROVED** [review]
+1

**Comment by doubledup** [comment]
Should we also bump `scale-info` to `2.5.0` in `snowbridge-router-primitives` and `snowbridge-inbound-queue`? Looks like it's [updated in the Cumulus PR](https://github.com/Snowfork/cumulus/pull/16/files#diff-f06ea007aeb785d3e84ef4aae51764780dd11a6a35171ad786f567b9e1c0ed7bL13-R13)

**Review by doubledup — APPROVED** [review]
LGTM otherwise!

**Comment by alistair-singh** [comment]
> Should we also bump `scale-info` to `2.5.0` in `snowbridge-router-primitives` and `snowbridge-inbound-queue`? Looks like it's [updated in the Cumulus PR](https://github.com/Snowfork/cumulus/pull/16/files#diff-f06ea007aeb785d3e84ef4aae51764780dd11a6a35171ad786f567b9e1c0ed7bL13-R13)
Nice catch! Added this in [595342e](https://github.com/Snowfork/snowbridge/pull/809/commits/595342e11d96c41f36fe4008bf0024633d69e759).

**Pull request merged**
