### PR TITLE
Use Milagro-BLS and Eth-ABI from crates.io

### PR DESCRIPTION
**Pull request by vgeddes**

### CODE REVIEW

**Review by yrong — APPROVED** [review]
Add a companion PR https://github.com/Snowfork/polkadot-sdk/pull/105 to update Cargo.lock or the CI task `zepter run check` will fail.

**Comment by vgeddes** [comment]
> Add a companion PR [Snowfork/polkadot-sdk#105](https://github.com/Snowfork/polkadot-sdk/pull/105) to update Cargo.lock or the CI task `zepter run check` will fail.

Nice catch!

**Comment by vgeddes** [comment]
> The diff looks a bit weird (includes my minimal spec changes in #1119), perhaps a rebase on `main` will fix it?

Thanks, seems to be resolved after my latest commits.

**Review by claravanstaden — APPROVED** [review]
Awesome, thanks @vgeddes!

**Review by alistair-singh — APPROVED** [review]
+1

**Pull request merged**
