### PR TITLE
Local setup for Westend

### PR DESCRIPTION
**Pull request by yrong**
Requires: https://github.com/Snowfork/polkadot-sdk/pull/163

### CODE REVIEW

**Comment by yrong** [comment]
Tested the E2E tests work as expected for westend local setup.

@claravanstaden  Just let you know I revert https://github.com/Snowfork/snowbridge/pull/1251 which does not apply to our forked polkadot-sdk or submit extrinsic will fail.  But we can upgrade polkadot-sdk to a more recent version and add that back in another PR.

**Review by alistair-singh — APPROVED** [review]
+1

**Comment by claravanstaden** [comment]
@yrong I have updated https://github.com/Snowfork/polkadot-sdk with the latest from upstream. Please let me know if it resolves the gsprc issue for you. :)

**Comment by yrong** [comment]
Hey Clara, thanks for the upgrade.  Though it still requires https://github.com/Snowfork/polkadot-sdk/pull/163/commits/c8f9fe0ccdfe581f3608d04b2eb04e61b8958a7f to include the gsprc fix.
 
 Just tested the e2e tests work as expected.

**Review by vgeddes — APPROVED** [review]
+1

**Pull request merged**
